-*- coding: utf-8 -*-

BBS ホームページ 改造

*  きっかけ

   アクセス数は増えているが、見学の問い合わせがない状況を打破したい。
   上程事項として、ホームページの「興味がある」ページを「入会するには(仮)」等へ変更して、見学募集だけでなく、会員申し込み・賛助会員申し込みへの導線も敷いていけるように改造したいです。時期は夏頃までには可否を出してもらいたいです。


*  当会ホームページへのアクセスのトップを占める参照元サイトのカウント数

   www.google.co.jp	1319
   search.yahoo.co.jp	1039
   sumidabbs.blogspot.jp	600
   www.facebook.com	311
   sumidabbs.blogspot.com	295
   m.facebook.com	239
   bbs-japan.org	210

   トップを占める参照元サイトを解析した結果、google と yahoo が飛び抜けていることがわかった。このことから検索エンジンによるアクセスが相当数いると判明。このカウント数は全期間を対象としている。


*  facebookについて

   一時期のトップアクセス数を稼いだ facebook からの流入は落ち着きを見せている。落ち着いた要因はfacebookが閉じたSNSサービスであることからフレンズの最終端までリーチしたためと考えられる。

   当初の設計思想では口コミから拡散が可能と予測していたが思ったよりも伸び代はなかった。

   伸び代がないとした裏付けはlike数の遷移が上げられる。

   like数を計測した結果、2013年4月11日にSNSサービスイン、2013年7月7日に50like到達、2014年10月7日に100like到達の遷移となっている。サービスインから3ヶ月で50like到達したが、50likeから100likeまでは15ヶ月の期間がかかった。単純計算でいけば3ヶ月で50likeを稼げるはずだが実測はそうなっていない。

   次のマイルストン、200likeは30ヶ月が必要と予測。

   以上からfacebookはあくまでブランディングページの側面しか持ちえないことが露見した。今後拡散サービスとしては期待しない。


*  どのチャンネルを活用すべきか

   現時点で使用しているチャネルは ブログ、ツイッター、フェイスブック の3つ。

   これらのチャネルからどれに注力を置くべきか。フェイスブックは先に上げた理由から落とす。

   ツイッターはつぶやきではなく、ブログの広報として利用しているため落とす。

   以上のことからブログを活用すべきと考察する。


*  会員数増大へ向けたインターネットメディアのありかた

   新規会員数を増大するにはインターネットメディアへのさらなる露出が必要である。
   インターネットメディアを利用するメリットはすぐに実現可能であることからガンガン使っていくべきと考える。

   さらなる露出を目標とするとしても単純に検索エンジン対策やブログ更新頻度を上げるだけでは効果が薄い。
   効果が薄いとする理由は、ブログへ来たユーザに対して「あ、やってみたい!」と思わせるだけのコンテンツが弱いため。

** 課題と対策

*** 課題1 どのように興味を持ってもらうか。

   対策1 面白そう、楽しそう、といった演出をかけてやってみたいと思わせる。楽しそうな雰囲気をブログ上に演出する。BBSの活動だけではなく、サークル的ノリのブログ記事をポストする。
   対策2 会員に対する要求仕様の明示、求める人材像の具体化(伊藤アイディア)

*** 課題2 検索エンジンへのヒット率

   対策1 投稿内容の多様性
   対策2 広告の利用

*** 課題3 参入障壁を下げる、定例会へ参加しやすくする

   対策1 ホームページの「興味がある」ページを「入会するには(仮)」等へ変更し、見学募集だけでなく、会員申し込み・賛助会員申し込みへの導線を実装。
   対策2 会員に対する要求仕様の明示、求める人材像の具体化(伊藤アイディア)


** 案

1. 導線の明示

   会員（賛助会員も含む）申込みまで導線を引くことで、具体的な入会資格・入会することのメリット・現在特に募集している人材（～スキルを持っている方、属性など）まで明記することが出来る。
   ＜現状>問い合わせ→回答→入会検討→入会　という流れではなく、
   ＜案＞問い合わせ・入会希望→回答→入会　という手数に減らして、「誰でも見学できるよ～」（あんまり効果ない）という形から、「～こんな人材を求めています。あなたが必要です。」と思えるような形にもっていきたい。

2. 会員になるメリットの具体化

3. 申請フォームのプルタブ化

   プルタブでまとめることは可能。しかし、フォームが同一内容（名前、フリカナ、メールアドレス）でいいかは議論の余地あり。
   また、プルタブに改造して入会希望者が増えるとは考えにくい。これまでの見学申し込みの方が参入障壁としては低いため。
   興味があるのページのフォームにプルタブみたいなのを導入して、見学申し込みと入会希望の入り口をまとめることは出来るのではという疑問。

4. 問い合わせのページ移設

   問い合わせのページの内容は連絡先の記載。これを当会についてのページへ移設する。
   問い合わせのページはすでにデットページ（アクセスされていない）となっているので、当会についてのAbout us 的なのにぶっ込むのもアリ。
   これによりメニューの分散を少なくし、意図的なクリック誘導がしやすくなるメリットがある。


*  memo


